### ISSUE TITLE
contact info missing

### ISSUE THREAD

**Issue by johrstrom** [buckipr/R_Working_Group#1]
Hi, I work for the [Ohio SuperComputer Center](https://www.osc.edu/) with does a lot with R and OSU and some of our staff are interested in this group.

However, the site does not provide any details on who to contact to get invited to the group.

**Comment by jarathomas** [comment]
Hello, Apologies for the delayed response!  Please feel free to contact me at thomas.3912@osu.edu and I connect you with our group.  Best wishes, Jason

**Comment by johrstrom** [comment]
No issues on the delay and thank you!

**Comment by jarathomas** [comment]
added contact info at bottom of readme

**Comment by johrstrom** [comment]
Thanks!
